### ISSUE TITLE
All blocks containing supertable is showing warning

### ISSUE THREAD

**Issue by johannesSolvr** [charliedevelopment/blockonomicon-super-table-adapter#1]
All blocks containing supertables are showing warnings, but are imported correctly.

**Comment by sbossarte** [comment]
Blocks may show a warning if the JSON definition file for a block doesn't match how all the fields would export in their current configuration. This can happen if a field updates to add new settings or options, or simply winds up with some rearranged properties.

Perhaps Super Table updated since the blocks you are using were created. Re-exporting should update the definition, especially if they are still importing as expected.
